### ISSUE TITLE
A way to check if a process is failed

### ISSUE THREAD

**Issue by rogierlommers** [elauqsap/workerpool#1]
Hey @elauqsap , thanks for your package. Love it.

I have a question though: what do you think about implementing a way to check if a process has failed for some reason. When I see your [example](https://github.com/elauqsap/workerpool/blob/master/example/example.go) , then I don't have a way to do something if `Process()` fails. So basically my question is, how would you handle error handling?

**Comment by elauqsap** [comment]
Hi @rogierlommers, glad to hear! Thank you for the kind words.

To your question, I guess it depends on what kind of data you are processing but for my use cases I was just logging the error. So I would implement a global logger and if an error arises in `Process()` I would catch it and log it. The [blog post](http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/) linked in the `README.md` from the original author of this code demonstrates this. Hope this helps!

Edit: It also comes down to your workflow. Do you need to stop if an error occurs? Is there an order to the data you are processing? If you are answering yes to these questions then forking and modifying the code for your needs is probably the best move.

**Comment by rogierlommers** [comment]
Thanks, will check it out.
